// Create Order
export const PAYMENT_CREATE_ORDER_REQUEST = "PAYMENT_CREATE_ORDER_REQUEST";
export const PAYMENT_CREATE_ORDER_SUCCESS = "PAYMENT_CREATE_ORDER_SUCCESS";
export const PAYMENT_CREATE_ORDER_FAIL = "PAYMENT_CREATE_ORDER_FAIL";

// Verify Payment
export const PAYMENT_VERIFY_REQUEST = "PAYMENT_VERIFY_REQUEST";
export const PAYMENT_VERIFY_SUCCESS = "PAYMENT_VERIFY_SUCCESS";
export const PAYMENT_VERIFY_FAIL = "PAYMENT_VERIFY_FAIL";

// Reset Payment State
export const PAYMENT_RESET = "PAYMENT_RESET";
